notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: bionic
language: c
matrix:
  include:
    - name: "9.5"
      env:
        PG_VERSION: 9.5
      addons:
        postgresql: "9.5"
    - name: "9.6"
      env:
        PG_VERSION: 9.6
        WAL_SUPPORTED: "yes"
      addons:
        postgresql: "9.6"
    - name: "10"
      env:
        PG_VERSION: 10
        WAL_SUPPORTED: "yes"
      addons:
        postgresql: "10"
    - name: "11"
      env:
        PG_VERSION: 11
        WAL_SUPPORTED: "yes"
    - name: "12"
      env:
        PG_VERSION: 12
        WAL_SUPPORTED: "yes"
    - name: "with Groonga master"
      env:
        PG_VERSION: 10
        WAL_SUPPORTED: "yes"
        GROONGA_MASTER: "yes"
      addons:
        postgresql: "10"
install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - |
    if [ "${GROONGA_MASTER}" != "yes" ]; then
      sudo apt install -qq -y \
        groonga-tokenizer-mecab \
        groonga-token-filter-stem
    fi
  - |
    if [ "${WAL_SUPPORTED}" = "yes" ]; then
      gem install test-unit
    fi
  - |
    case ${PG_VERSION} in
      11|12)
        sudo service postgresql stop
        sudo apt purge postgresql-{9.3,9.4,9.5,9.6,10}
        sudo apt purge postgresql-client-{9.3,9.4,9.5,9.6,10}
        sudo apt install -V \
          libmsgpack-dev \
          postgresql-${PG_VERSION} \
          postgresql-client-${PG_VERSION} \
          postgresql-server-dev-${PG_VERSION}
        sudo systemctl start postgresql start ${PG_VERSION}
        sudo -u postgres -H psql -c "CREATE ROLE travis SUPERUSER LOGIN;"
        ;;
      *)
        sudo apt install -V \
          libmsgpack-dev \
          postgresql-server-dev-${PG_VERSION}
        ;;
    esac
  - PKG_CONFIG_PATH=$PWD/data/travis/pkgconfig make DEBUG=1 HAVE_MSGPACK=1
  - sudo make install
script:
  - |
    if [ "${WAL_SUPPORTED}" != "yes" ]; then
      rm -rf sql/function/wal-apply/
      rm -rf sql/function/wal-truncate/
      rm -rf sql/function/set-writable/
    fi
  - sudo -u postgres -H mkdir -p /tmp/space
  - |
    # (for i in $(seq 600)
    #  do
    #    sleep 1
    #    df -h | grep ramfs
    #  done) &
    PG_REGRESS_DIFF_OPTS="-u" \
      make installcheck \
        TMP_DIR=/tmp \
        SETUP_TMP_DIR=no \
        EXTRA_REGRESS_OPTS="--launcher=$(pwd)/test/short-pgappname"
  - |
    if [ "${WAL_SUPPORTED}" = "yes" ]; then
      PATH=/usr/lib/postgresql/$PG_VERSION/bin:$PATH test/run-test.rb
    fi
after_failure:
  - cat regression.diffs
#  - sudo cat /var/ramfs/postgresql/${PG_VERSION}/main/pgroonga.log
